// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTt8MOINtuDSszAC6qtJQRjLjk4z8pdhQ',
    appId: '1:450934451399:web:7404c168f7439392a262e2',
    messagingSenderId: '450934451399',
    projectId: 'notice-board-fa6ce',
    authDomain: 'notice-board-fa6ce.firebaseapp.com',
    storageBucket: 'notice-board-fa6ce.appspot.com',
    measurementId: 'G-FH1JVQEP0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwQRDcG6q5on0Cx8OqMP8Ct4WJU5F2YB0',
    appId: '1:450934451399:android:fc18547b15976c54a262e2',
    messagingSenderId: '450934451399',
    projectId: 'notice-board-fa6ce',
    storageBucket: 'notice-board-fa6ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYXeXnvML4rFRrE7QgLkN_bJ--vktka2w',
    appId: '1:450934451399:ios:0e6c859b69bf1a89a262e2',
    messagingSenderId: '450934451399',
    projectId: 'notice-board-fa6ce',
    storageBucket: 'notice-board-fa6ce.appspot.com',
    iosBundleId: 'com.example.boardProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYXeXnvML4rFRrE7QgLkN_bJ--vktka2w',
    appId: '1:450934451399:ios:0e6c859b69bf1a89a262e2',
    messagingSenderId: '450934451399',
    projectId: 'notice-board-fa6ce',
    storageBucket: 'notice-board-fa6ce.appspot.com',
    iosBundleId: 'com.example.boardProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTt8MOINtuDSszAC6qtJQRjLjk4z8pdhQ',
    appId: '1:450934451399:web:aa1b363e7902b348a262e2',
    messagingSenderId: '450934451399',
    projectId: 'notice-board-fa6ce',
    authDomain: 'notice-board-fa6ce.firebaseapp.com',
    storageBucket: 'notice-board-fa6ce.appspot.com',
    measurementId: 'G-Y2R8RTR22T',
  );
}
